---
# tasks file for ansible-kibana
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: config_kibana.yml
  when: kibana_config

- include: plugins.yml
  when: kibana_manage_plugins

- name: Ensuring Kibana Service Is Started And Enabled On Boot
  service:
    name: "kibana"
    enabled: yes
    state: "started"
  become: true
